### ISSUE TITLE
Update references to VSTS in README.md

### ISSUE THREAD

**Issue by lodejard** [Microsoft/Atlas#39]
The README.md text was written before the Azure DevOps branding was announced. There are a lot of places where it should be updated.

Some things might be a little tricky... Distinguishing between Azure DevOps the product, and DevOps the role... Also, if there are `Azure DevOps` API and `Azure Active Directory` API, what do you call the `Azure` API that's distinct? `Azure Resources` API? or `Azure Resource Manager` API?

**Comment by james-flynn-ie** [comment]
Submitted PR, ready for review and merge.

**Comment by lodejard** [comment]
Fixed in #42
